# Generated by Django 5.2.10 on 2026-02-02 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_pep',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='origin_funds',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('AH', 'Ahorros'), ('CC', 'Corriente'), ('DE', 'Depósito Electrónico (Nequi/Daviplata)')], default='AH', max_length=2, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_code',
            field=models.CharField(blank=True, choices=[('007', 'Bancolombia (007)'), ('001', 'Banco de Bogotá (001)'), ('051', 'Davivienda (051)'), ('013', 'BBVA Colombia (013)'), ('023', 'Banco de Occidente (023)'), ('002', 'Banco Popular (002)'), ('052', 'Banco AV Villas (052)'), ('032', 'Banco Caja Social (032)'), ('507', 'Nequi (507)'), ('551', 'Daviplata (551)'), ('019', 'Scotiabank Colpatria (019)'), ('999', 'Otro / No Listado')], help_text='Código ACH del banco para pagos de comisiones.', max_length=3, verbose_name='Banco (Nómina)'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='Foto Perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, help_text='Sin guiones ni espacios.', max_length=30, verbose_name='Número de Cuenta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular de Contacto'),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT (Persona Jurídica)'), ('PAS', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=5, verbose_name='Tipo Documento')),
                ('document_id', models.CharField(max_length=20, unique=True, verbose_name='Número Identificación')),
                ('expedition_date', models.DateField(blank=True, null=True, verbose_name='Fecha Expedición')),
                ('expedition_city', models.CharField(blank=True, max_length=50, verbose_name='Ciudad Expedición')),
                ('person_type', models.CharField(choices=[('PN', 'Persona Natural'), ('PJ', 'Persona Jurídica')], default='PN', max_length=2, verbose_name='Tipo Persona')),
                ('tax_regime', models.CharField(choices=[('49', 'No Responsable de IVA (Antig. Simplificado)'), ('48', 'Responsable de IVA (Común)'), ('GC', 'Gran Contribuyente'), ('ST', 'Régimen Simple de Tributación')], default='49', max_length=5, verbose_name='Régimen Tributario')),
                ('ciiu_code', models.CharField(blank=True, help_text='Código actividad económica RUT', max_length=10, verbose_name='Código CIIU')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección Fiscal')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('department', models.CharField(default='Antioquia', max_length=50, verbose_name='Departamento')),
                ('is_pep', models.BooleanField(default=False, help_text='Persona Expuesta Políticamente', verbose_name='Es PEP?')),
                ('origin_funds', models.TextField(blank=True, verbose_name='Origen de Fondos')),
                ('economic_activity', models.CharField(blank=True, max_length=100, verbose_name='Ocupación / Actividad')),
                ('is_identity_verified', models.BooleanField(default=False, verbose_name='Biometría OK')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
