# Generated by Django 5.2.11 on 2026-02-09 16:06

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_code',
            field=models.CharField(blank=True, choices=[('1007', 'Bancolombia'), ('1001', 'Banco de Bogota'), ('1002', 'Banco Popular'), ('1006', 'Itau'), ('1009', 'Citibank'), ('1012', 'Banco GNB Sudameris'), ('1013', 'BBVA Colombia'), ('1019', 'Scotiabank Colpatria'), ('1023', 'Banco de Occidente'), ('1032', 'Banco Caja Social'), ('1040', 'Banco Agrario'), ('1051', 'Davivienda'), ('1052', 'Banco AV Villas'), ('1047', 'Banco Mundo Mujer'), ('1053', 'Banco W'), ('1059', 'Bancamia'), ('1060', 'Banco Pichincha'), ('1061', 'Bancoomeva'), ('1062', 'Banco Falabella'), ('1063', 'Banco Finandina'), ('1066', 'Banco Cooperativo Coopcentral'), ('1069', 'Banco Serfinanza'), ('1070', 'Lulo Bank'), ('1507', 'Nequi'), ('1551', 'Daviplata'), ('1151', 'RappiPay'), ('1809', 'Nu Colombia'), ('1560', 'Pibank'), ('1558', 'Ban100'), ('1808', 'Bold'), ('1291', 'Coofinep'), ('1292', 'Confiar'), ('1289', 'Cootrafa'), ('1283', 'CFA Cooperativa Financiera'), ('9999', 'Otro / No Listado')], help_text='Código ACH del banco para pagos de comisiones.', max_length=4, verbose_name='Banco (Nómina)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=core.storages.PublicMediaStorage(), upload_to='users/photos/', verbose_name='Foto Perfil'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
