# Generated by Django 5.2.11 on 2026-02-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_update_bank_codes_ach_cenit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('SUPERVISOR', 'Supervisor'), ('TESORERIA', 'Tesoreria'), ('DIRECTOR', 'Director Comercial'), ('ASESOR', 'Asesor Comercial'), ('CLIENTE', 'Cliente Comprador')], default='CLIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='code',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('SUPERVISOR', 'Supervisor'), ('TESORERIA', 'Tesoreria'), ('DIRECTOR', 'Director Comercial'), ('ASESOR', 'Asesor Comercial'), ('CLIENTE', 'Cliente Comprador')], max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(choices=[('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('SUPERVISOR', 'Supervisor'), ('TESORERIA', 'Tesoreria'), ('DIRECTOR', 'Director Comercial'), ('ASESOR', 'Asesor Comercial'), ('CLIENTE', 'Cliente Comprador')], max_length=20, verbose_name='Rol')),
                ('permission_key', models.CharField(max_length=200, verbose_name='Permiso')),
                ('allowed', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Etiqueta')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='Ruta')),
            ],
            options={
                'unique_together': {('role_code', 'permission_key')},
            },
        ),
    ]
