# Generated by Codex on 2026-02-09
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_commission_roles_scales'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCommissionRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='%')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_roles', to='inventory.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.commissionrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectcommissionrole',
            constraint=models.UniqueConstraint(fields=('project', 'role'), name='unique_commission_role_per_project'),
        ),
    ]
