# Generated by Codex on 2026-02-09
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_project_commission_roles'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salecommissionscale',
            name='unique_commission_scale_per_sale_user_role',
        ),
        migrations.AddConstraint(
            model_name='salecommissionscale',
            constraint=models.UniqueConstraint(fields=('sale', 'role'), name='unique_commission_scale_per_sale_role'),
        ),
    ]
