# Generated by Django 5.2.11 on 2026-02-09 18:45

import core.storages
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_unique_commission_role_per_sale'),
        ('inventory', '0007_project_mora_rate_monthly_alter_finishoption_image_and_more'),
        ('sales', '0017_alter_sale_contract_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectcommissionrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salecommissionscale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='inventory.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor recibido')),
                ('date_registered', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('date_paid', models.DateField(verbose_name='Fecha real de pago')),
                ('evidence', models.ImageField(blank=True, storage=core.storages.PublicMediaStorage(), upload_to='recaudos/', verbose_name='Soporte')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('surplus', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Saldo a favor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Elaborado por')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.paymentmethod', verbose_name='Forma de pago')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='sales.sale')),
            ],
            options={
                'ordering': ['-date_registered'],
            },
        ),
        migrations.CreateModel(
            name='PaymentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(choices=[('MORA', 'Interés de mora'), ('INT', 'Interés corriente'), ('CAP', 'Capital')], max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto aplicado')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='sales.paymentschedule')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='finance.paymentreceipt')),
            ],
            options={
                'ordering': ['schedule_item__n', 'concept'],
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
