# Generated by Django 5.2.11 on 2026-02-09 20:29

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_commissionrole_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Hash del archivo'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='evidence',
            field=models.FileField(blank=True, storage=core.storages.PrivateMediaStorage(), upload_to='recaudos/', verbose_name='Soporte (PDF)'),
        ),
    ]
