# Generated by Django 5.2.11 on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_paymentreceipt_file_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreasuryReceiptRequestState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_request_id", models.CharField(db_index=True, max_length=120, unique=True, verbose_name="ID solicitud externa")),
                ("status", models.CharField(choices=[("PENDING", "Pendiente"), ("VALIDATED", "Validada"), ("REQUIRES_MANUAL", "Requiere revisión manual"), ("BLOCKED", "Bloqueada"), ("RECEIPT_CREATED", "Recibo creado")], default="PENDING", max_length=24, verbose_name="Estado")),
                ("validation_result", models.CharField(blank=True, choices=[("sin_alertas", "Sin alertas"), ("con_alertas", "Con alertas"), ("bloqueo", "Bloqueo")], default="", max_length=20, verbose_name="Resultado de validación")),
                ("alerts", models.JSONField(blank=True, default=list, verbose_name="Alertas")),
                ("form_token", models.CharField(blank=True, max_length=255, verbose_name="Token de formulario")),
                ("idempotency_key", models.CharField(blank=True, max_length=120, verbose_name="Llave de idempotencia")),
                ("validation_payload", models.JSONField(blank=True, default=dict, verbose_name="Payload validación")),
                ("validation_response", models.JSONField(blank=True, default=dict, verbose_name="Respuesta validación")),
                ("receipt_payload", models.JSONField(blank=True, default=dict, verbose_name="Payload creación")),
                ("receipt_response", models.JSONField(blank=True, default=dict, verbose_name="Respuesta creación")),
                ("last_error", models.TextField(blank=True, verbose_name="Último error")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
