# Generated by Django 5.2.11 on 2026-02-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_treasuryreceiptrequeststate"),
        ("sales", "0020_alter_saledocument_date_alter_saledocument_id"),
        ("users", "0006_alter_user_role_alter_userrole_code_rolepermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="treasuryreceiptrequeststate",
            name="abono_capital",
            field=models.BooleanField(default=False, verbose_name="Abono a capital"),
        ),
        migrations.AddField(
            model_name="treasuryreceiptrequeststate",
            name="advisor_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Asesor"),
        ),
        migrations.AddField(
            model_name="treasuryreceiptrequeststate",
            name="amount_reported",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Valor reportado"),
        ),
        migrations.AddField(
            model_name="treasuryreceiptrequeststate",
            name="client_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="Cliente"),
        ),
        migrations.AddField(
            model_name="treasuryreceiptrequeststate",
            name="condonacion_mora",
            field=models.BooleanField(default=False, verbose_name="Condonación de mora"),
        ),
        migrations.AddField(
            model_name="treasuryreceiptrequeststate",
            name="created_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_receipt_requests", to="users.user"),
        ),
        migrations.AddField(
            model_name="treasuryreceiptrequeststate",
            name="linked_receipt",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="source_requests", to="finance.paymentreceipt"),
        ),
        migrations.AddField(
            model_name="treasuryreceiptrequeststate",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha de pago reportada"),
        ),
        migrations.AddField(
            model_name="treasuryreceiptrequeststate",
            name="project_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="Proyecto"),
        ),
        migrations.AddField(
            model_name="treasuryreceiptrequeststate",
            name="review_reason",
            field=models.TextField(blank=True, verbose_name="Motivo revisión manual"),
        ),
        migrations.AddField(
            model_name="treasuryreceiptrequeststate",
            name="sale",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="receipt_requests", to="sales.sale"),
        ),
        migrations.AddField(
            model_name="treasuryreceiptrequeststate",
            name="source",
            field=models.CharField(default="asesor", max_length=20, verbose_name="Canal"),
        ),
        migrations.AddField(
            model_name="treasuryreceiptrequeststate",
            name="support_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="URL soporte"),
        ),
    ]
