# Generated by Django 5.2.11 on 2026-02-18

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_receipt_request_module_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="treasuryreceiptrequeststate",
            name="support_evidence",
            field=models.FileField(
                blank=True,
                storage=core.storages.PrivateMediaStorage(),
                upload_to="receipt_requests/",
                verbose_name="Soporte (PDF)",
            ),
        ),
    ]
