# Generated by Django 5.2.10 on 2026-01-26 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Acabado')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Adicional')),
            ],
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Prototipo')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio Base')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Proyecto')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('construction_progress', models.PositiveIntegerField(default=0, verbose_name='Avance %')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('block', models.CharField(blank=True, max_length=20, verbose_name='Torre')),
                ('status', models.CharField(choices=[('DISP', 'Disponible'), ('VEND', 'Vendida')], default='DISP', max_length=4)),
                ('house_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.housetype')),
            ],
        ),
        migrations.AddField(
            model_name='housetype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.project'),
        ),
    ]
