# Generated by Django 5.2.10 on 2026-02-02 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finishoption',
            options={'ordering': ['category__order', 'name'], 'verbose_name': 'Opción de Acabado', 'verbose_name_plural': 'Opciones de Acabados'},
        ),
        migrations.RemoveField(
            model_name='house',
            name='block',
        ),
        migrations.RemoveField(
            model_name='house',
            name='number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='construction_progress',
        ),
        migrations.AddField(
            model_name='finishoption',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle Técnico'),
        ),
        migrations.AddField(
            model_name='finishoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='finishes/', verbose_name='Foto Referencia'),
        ),
        migrations.AddField(
            model_name='finishoption',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='finishoption',
            name='max_value_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor máximo permitido para este acabado por unidad (ej. piso).', max_digits=12, null=True, verbose_name='Monto Máximo por Unidad'),
        ),
        migrations.AddField(
            model_name='house',
            name='address_details',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación Exacta'),
        ),
        migrations.AddField(
            model_name='house',
            name='current_progress',
            field=models.PositiveIntegerField(default=0, verbose_name='Avance Físico (%)'),
        ),
        migrations.AddField(
            model_name='house',
            name='lot_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Predio/Lote'),
        ),
        migrations.AddField(
            model_name='house',
            name='real_estate_registration',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matrícula Inmobiliaria'),
        ),
        migrations.AddField(
            model_name='housetype',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Área Construida (m2)'),
        ),
        migrations.AddField(
            model_name='housetype',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Baños'),
        ),
        migrations.AddField(
            model_name='housetype',
            name='blueprint_file',
            field=models.FileField(blank=True, null=True, upload_to='blueprints/', verbose_name='Anexo A: Planos'),
        ),
        migrations.AddField(
            model_name='housetype',
            name='construction_duration_months',
            field=models.PositiveIntegerField(blank=True, default=6, null=True, verbose_name='Plazo Ejecución (Meses)'),
        ),
        migrations.AddField(
            model_name='housetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Arquitectónica'),
        ),
        migrations.AddField(
            model_name='housetype',
            name='rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Habitaciones'),
        ),
        migrations.AddField(
            model_name='housetype',
            name='specs_file',
            field=models.FileField(blank=True, null=True, upload_to='specs/', verbose_name='Anexo B: Cantidades'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_grace_days',
            field=models.PositiveIntegerField(default=15, verbose_name='Días Gracia Mora (Cláusula 5)'),
        ),
        migrations.AddField(
            model_name='project',
            name='penalty_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='% Penalidad (Cláusula 9)'),
        ),
        migrations.AddField(
            model_name='project',
            name='structural_guarantee_years',
            field=models.PositiveIntegerField(default=10, verbose_name='Años Garantía Estructural'),
        ),
        migrations.AlterField(
            model_name='finishoption',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre del Acabado'),
        ),
        migrations.AlterField(
            model_name='finishoption',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Adicional'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.housetype'),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('DISP', 'Disponible'), ('RESV', 'Reservada/Legalización'), ('CONST', 'En Construcción'), ('ENTR', 'Entregada')], default='DISP', max_length=5),
        ),
        migrations.AlterField(
            model_name='housetype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio Base Construcción'),
        ),
        migrations.AlterField(
            model_name='housetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre Prototipo'),
        ),
        migrations.AlterField(
            model_name='housetype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_types', to='inventory.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Ciudad / Ubicación'),
        ),
        migrations.CreateModel(
            name='FinishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Categoría')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden en Contrato')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finish_categories', to='inventory.project')),
            ],
            options={
                'verbose_name': 'Categoría de Acabado',
                'verbose_name_plural': 'Categorías de Acabados',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='finishoption',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='inventory.finishcategory'),
        ),
        migrations.CreateModel(
            name='HouseFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='house_finishes', to='inventory.finishoption')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_finishes', to='inventory.house')),
            ],
            options={
                'unique_together': {('house', 'finish')},
            },
        ),
        migrations.AddField(
            model_name='house',
            name='finishes',
            field=models.ManyToManyField(blank=True, related_name='houses', through='inventory.HouseFinish', to='inventory.finishoption'),
        ),
    ]
