# Generated by Django 5.2.11 on 2026-02-09 18:45

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_project_max_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mora_rate_monthly',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Tasa mora mensual (%)'),
        ),
        migrations.AlterField(
            model_name='finishoption',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storages.PublicMediaStorage(), upload_to='finishes/', verbose_name='Foto Referencia'),
        ),
        migrations.AlterField(
            model_name='housetype',
            name='blueprint_file',
            field=models.FileField(blank=True, null=True, storage=core.storages.PrivateMediaStorage(), upload_to='blueprints/', verbose_name='Anexo A: Planos'),
        ),
        migrations.AlterField(
            model_name='housetype',
            name='specs_file',
            field=models.FileField(blank=True, null=True, storage=core.storages.PrivateMediaStorage(), upload_to='specs/', verbose_name='Anexo B: Cantidades'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.storages.PublicMediaStorage(), upload_to='projects/', verbose_name='Logo del Proyecto'),
        ),
    ]
