# Generated by Django 5.2.11 on 2026-02-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_project_mora_rate_monthly_alter_finishoption_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='construction_start_months',
            field=models.PositiveIntegerField(default=24, help_text='Meses después de la firma del contrato para iniciar la construcción', verbose_name='Meses para inicio de obra (desde contrato)'),
        ),
    ]
