# Generated by Django 5.2.11 on 2026-02-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_add_construction_start_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='construction_duration_months',
            field=models.PositiveIntegerField(default=6, help_text='Duración estimada de la construcción (puede variar por tipo de casa)', verbose_name='Meses de ejecución de obra'),
        ),
    ]
