# Generated by Django 5.2.11 on 2026-02-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_add_construction_duration_months_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishoption',
            name='unit',
            field=models.CharField(blank=True, help_text='Ej: m², unidad, ml, global', max_length=30, verbose_name='Unidad'),
        ),
    ]
