# Generated by Codex on 2026-02-10
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_add_unit_to_finishoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="finishcategory",
            name="is_required",
            field=models.BooleanField(default=False, verbose_name="Obligatoria"),
        ),
    ]
