# Generated by Codex on 2026-02-10
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_finishcategory_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="finishcategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activa"),
        ),
    ]
