# Generated by Django 5.2.11 on 2026-02-26 03:08

from django.db import migrations, models


def copy_project_max_discount_to_house_types(apps, schema_editor):
    HouseType = apps.get_model("inventory", "HouseType")
    for house_type in HouseType.objects.select_related("project").all():
        house_type.max_discount_percent = house_type.project.max_discount_percent or 0
        house_type.save(update_fields=["max_discount_percent"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_finishcategory_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='housetype',
            name='max_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Máx. descuento (%)'),
        ),
        migrations.RunPython(copy_project_max_discount_to_house_types, migrations.RunPython.noop),
    ]
