# Generated by Django 5.2.10 on 2026-01-26 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio Final')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('COT', 'Cotización'), ('ID', 'Verificando Identidad'), ('SIGN', 'Firmando'), ('ACT', 'Venta Activa')], default='COT', max_length=5)),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('didit_session', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SaleFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
