# Generated by Django 5.2.10 on 2026-02-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_contractparty_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractparty',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
    ]
