# Generated by Django 5.2.11 on 2026-02-09 18:45

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_salelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='contract_pdf',
            field=models.FileField(blank=True, null=True, storage=core.storages.PrivateMediaStorage(), upload_to='contracts/'),
        ),
    ]
