# Generated by Codex on 2026-02-10
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import core.storages


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_sale_contract_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(storage=core.storages.PrivateMediaStorage(), upload_to='sales_documents/', verbose_name='Documento (PDF)')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Hash del archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.sale')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_sale_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='saledocument',
            constraint=models.UniqueConstraint(fields=('sale', 'file_hash'), name='unique_sale_document_hash_per_sale'),
        ),
    ]
