# Generated by Django 5.2.11 on 2026-02-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_contractparty_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledocument',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
