# Generated by Django 5.2.10 on 2026-02-05 15:59

import core.storages
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('LOGO', 'Logotipo'), ('SIGNATURE', 'Firma'), ('SEAL', 'Sello'), ('BACKGROUND', 'Fondo'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Categoría de Asset',
                'verbose_name_plural': 'Categorías de Assets',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.SlugField(unique=True, verbose_name='Código')),
                ('context_builder', models.CharField(help_text='Ruta completa a la clase, ej: documents.context_builders.sale_contract.SaleContractContext', max_length=255, verbose_name='Context Builder')),
                ('default_page_size', models.CharField(choices=[('A4', 'A4 (210mm x 297mm)'), ('letter', 'Carta (8.5in x 11in)'), ('legal', 'Oficio (8.5in x 14in)'), ('A3', 'A3 (297mm x 420mm)')], default='A4', max_length=20, verbose_name='Tamaño de página')),
                ('default_orientation', models.CharField(choices=[('portrait', 'Vertical'), ('landscape', 'Horizontal')], default='portrait', max_length=20, verbose_name='Orientación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('html_content', models.TextField(blank=True, default='', verbose_name='Contenido HTML')),
                ('css_content', models.TextField(blank=True, default='', verbose_name='Contenido CSS')),
                ('components_json', models.JSONField(blank=True, help_text='Estado serializado del editor GrapesJS', null=True, verbose_name='Componentes GrapesJS')),
                ('styles_json', models.JSONField(blank=True, help_text='Estilos serializados del editor GrapesJS', null=True, verbose_name='Estilos GrapesJS')),
                ('page_size', models.CharField(choices=[('A4', 'A4 (210mm x 297mm)'), ('letter', 'Carta (8.5in x 11in)'), ('legal', 'Oficio (8.5in x 14in)'), ('A3', 'A3 (297mm x 420mm)')], default='A4', max_length=20, verbose_name='Tamaño de página')),
                ('orientation', models.CharField(choices=[('portrait', 'Vertical'), ('landscape', 'Horizontal')], default='portrait', max_length=20, verbose_name='Orientación')),
                ('margin_top', models.DecimalField(decimal_places=2, default=2.5, max_digits=4, verbose_name='Margen superior (cm)')),
                ('margin_bottom', models.DecimalField(decimal_places=2, default=2.5, max_digits=4, verbose_name='Margen inferior (cm)')),
                ('margin_left', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='Margen izquierdo (cm)')),
                ('margin_right', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='Margen derecho (cm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='documents.documenttype', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Plantilla PDF',
                'verbose_name_plural': 'Plantillas PDF',
                'ordering': ['document_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('file', models.ImageField(storage=core.storages.PublicMediaStorage(), upload_to='document_assets/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ancho (px)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Alto (px)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='documents.assetcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Asset de Plantilla',
                'verbose_name_plural': 'Assets de Plantillas',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la variable (sin espacios ni caracteres especiales)', max_length=50, verbose_name='Nombre')),
                ('label', models.CharField(help_text='Etiqueta descriptiva para mostrar en el editor', max_length=100, verbose_name='Etiqueta')),
                ('description', models.CharField(blank=True, help_text='Descripción de qué representa esta variable', max_length=255, verbose_name='Descripción')),
                ('data_type', models.CharField(choices=[('STRING', 'Texto'), ('NUMBER', 'Número'), ('DECIMAL', 'Decimal'), ('DATE', 'Fecha'), ('BOOLEAN', 'Sí/No'), ('LIST', 'Lista')], default='STRING', max_length=20, verbose_name='Tipo de dato')),
                ('default_value', models.CharField(blank=True, max_length=255, verbose_name='Valor por defecto')),
                ('is_required', models.BooleanField(default=False, help_text='Si es True, debe proveerse al generar el PDF', verbose_name='Requerida')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_variables', to='documents.pdftemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Variable Personalizada',
                'verbose_name_plural': 'Variables Personalizadas',
                'ordering': ['template', 'name'],
                'unique_together': {('template', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Número de versión')),
                ('html_content', models.TextField(verbose_name='Contenido HTML')),
                ('css_content', models.TextField(blank=True, default='', verbose_name='Contenido CSS')),
                ('components_json', models.JSONField(blank=True, null=True, verbose_name='Componentes GrapesJS')),
                ('styles_json', models.JSONField(blank=True, null=True, verbose_name='Estilos GrapesJS')),
                ('change_description', models.CharField(blank=True, max_length=255, verbose_name='Descripción del cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.pdftemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Versión de Plantilla',
                'verbose_name_plural': 'Versiones de Plantilla',
                'ordering': ['-version_number'],
                'unique_together': {('template', 'version_number')},
            },
        ),
    ]
