# Generated by Django 5.2.11 on 2026-02-06 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_refactor_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateContextAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, verbose_name='Alias')),
                ('app_label', models.CharField(max_length=100, verbose_name='App')),
                ('model_label', models.CharField(max_length=100, verbose_name='Modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_aliases', to='documents.pdftemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Alias de Contexto',
                'verbose_name_plural': 'Aliases de Contexto',
                'ordering': ['template', 'alias'],
                'unique_together': {('template', 'alias')},
            },
        ),
    ]
